# Generated by Django 4.2.1 on 2023-05-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_rename_origin_url_link_original_url_alter_link_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='owner',
            field=models.CharField(max_length=32),
        ),
    ]
