# Generated by Django 4.2.1 on 2023-05-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='fake_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
