# Generated by Django 4.2.1 on 2023-05-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_link_fake_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='fake_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
