# Generated by Django 4.2.1 on 2023-05-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_link_fake_url_alter_link_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='owner',
            new_name='name',
        ),
    ]
