# Generated by Django 4.2.1 on 2023-05-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_rename_owner_link_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-id',)},
        ),
    ]
